# Generated by Django 3.0.8 on 2021-05-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ip',
            field=models.CharField(default=1, max_length=50, verbose_name='Определятор'),
            preserve_default=False,
        ),
    ]
